# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d76e9645392e1fb114fd3d22c13b98cff6a8544a2276ec9c5625bcc1d94b6791b9c7a9412f7a7fa5249c5e84885e5b7acfbdde84c50ca5d7a0660c2248cb5b4

test:
  secret_key_base: 8b8003077fe09817317bdc7be8d188ea6f80bed17c215d213239afe38159ea8dc8a38256eda1fcf4ccc82162ad9c1002a66af0d85135584f68ee241a94529802

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
